apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/Deimos-code-analyzer/Bedrock.git
    targetRevision: main
    path: k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-ns
  syncPolicy:
    automated: {}   # enables auto-sync (optional)