apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=ayushjsrtia/code-analyzer-frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^.*$
spec:
  destination:
    namespace: code-analyzer
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Deimos-code-analyzer/Frontend.git
    path: k8s/
    targetRevision: HEAD
    kustomize: {}
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true