name: Manual Rerun

on:
  workflow_dispatch:

jobs:
  rerun:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run job
        run: |
          sh setup/runner.fix